const mongoose = require('mongoose');

// Define schema matching your data structure
const episodeSchema = new mongoose.Schema({
  EPISODE: String,
  TITLE: String,
  APPLE_FRAME: Number,
  AURORA_BOREALIS: Number,
  BARN: Number,
  BEACH: Number,
  BOAT: Number,
  BRIDGE: Number,
  BUILDING: Number,
  BUSHES: Number,
  CABIN: Number,
  CACTUS: Number,
  CIRCLE_FRAME: Number,
  CIRRUS: Number,
  CLIFF: Number,
  CLOUDS: Number,
  CONIFER: Number,
  CUMULUS: Number,
  DECIDUOUS: Number,
  DIANE_ANDRE: Number,
  DOCK: Number,
  DOUBLE_OVAL_FRAME: Number,
  FARM: Number,
  FENCE: Number,
  FIRE: Number,
  FLORIDA_FRAME: Number,
  FLOWERS: Number,
  FOG: Number,
  FRAMED: Number,
  GRASS: Number,
  GUEST: Number,
  HALF_CIRCLE_FRAME: Number,
  HALF_OVAL_FRAME: Number,
  HILLS: Number,
  LAKE: Number,
  LAKES: Number,
  LIGHTHOUSE: Number,
  MILL: Number,
  MOON: Number,
  MOUNTAIN: Number,
  MOUNTAINS: Number,
  NIGHT: Number,
  OCEAN: Number,
  OVAL_FRAME: Number,
  PALM_TREES: Number,
  PATH: Number,
  PERSON: Number,
  PORTRAIT: Number,
  RECTANGLE_3D_FRAME: Number,
  RECTANGULAR_FRAME: Number,
  RIVER: Number,
  ROCKS: Number,
  SEASHELL_FRAME: Number,
  SNOW: Number,
  SNOWY_MOUNTAIN: Number,
  SPLIT_FRAME: Number,
  STEVE_ROSS: Number,
  STRUCTURE: Number,
  SUN: Number,
  TOMB_FRAME: Number,
  TREE: Number,
  TREES: Number,
  TRIPLE_FRAME: Number,
  WATERFALL: Number,
  WAVES: Number,
  WINDMILL: Number,
  WINDOW_FRAME: Number,
  WINTER: Number,
  WOOD_FRAMED: Number,
});

// Create a model based on the schema
const Episode = mongoose.model('Episode', episodeSchema, 'episodes_data');

module.exports = Episode;
