CREATE TABLE colors_used (
    id INT PRIMARY KEY,
	painting_index INT,
    img_src TEXT,
    painting_title TEXT,
    season INT,
    episode INT,
    num_colors INT,
    youtube_src TEXT,
    colors TEXT,
    color_hex TEXT,
    black_gesso BOOLEAN,
    bright_red BOOLEAN,
    burnt_umber BOOLEAN,
    cadmium_yellow BOOLEAN,
    dark_sienna BOOLEAN,
    indian_red BOOLEAN,
    indian_yellow BOOLEAN,
    liquid_black BOOLEAN,
    liquid_clear BOOLEAN,
    midnight_black BOOLEAN,
    phthalo_blue BOOLEAN,
    phthalo_green BOOLEAN,
    prussian_blue BOOLEAN,
    sap_green BOOLEAN,
    titanium_white BOOLEAN,
    van_dyke_brown BOOLEAN,
    yellow_ochre BOOLEAN,
    alizarin_crimson BOOLEAN
);
